{{- if .Values.pspEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-psp
  labels:
{{ include "prometheus-operator.labels" . | indent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "prometheus-operator.fullname" . }}
{{- end }}
