{{- if .Values.pspEnabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-psp
  labels:
{{ include "prometheus-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-operator.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
